### ISSUE TITLE
在CentOS6.5上安装之后启动出现Error: Cannot find module 'think-logger3'

### ISSUE THREAD

**Issue by glovebx** [tumobi/nideshop#11]
单独执行  npm install think-logger3 --no-optional成功之后启动，同样报错找不到模块

部分报错信息如下：

module.js:471
    throw err;
    ^

Error: Cannot find module 'think-logger3'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/html/nideshop/node_modules/thinkjs/lib/loader.js:2:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 2.6.32-696.1.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! thinkjs-application@1.0.0 start: `node development.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the thinkjs-application@1.0.0 start script 'node development.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thinkjs-application package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node development.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thinkjs-application
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thinkjs-application
npm ERR! There is likely additional logging output above.

**Comment by glovebx** [comment]
已经解决，从github上下载think-logger3模块，将src目录拷贝到工程的think-logger3模块里面即可

**Comment by xjl271314** [comment]
抱歉打扰，您把后台的nodejs端直接部署到centOs系统成功吗？我这有个问题不知道证码解决？
